# port
server:
  port: 8080

# database 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rezoom?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    #    for sql logging
    #    url: jdbc:log4jdbcmysql://localhost:3306/rezoom?useSSL=false&characterEncoding=UTF-8
    #    username: root
    #    password: 1234
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
