# port
server:
  port: 8080

# database 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rezoom?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    #    for sql logging
    #    url: jdbc:log4jdbcmysql://localhost:3306/rezoom?useSSL=false&characterEncoding=UTF-8
    #    username: root
    #    password: 1234
    #    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# social oauth2
facebook:
  client:
    clientId: 490325814748030
    clientSecret: 3c4dd3da27469259bd0c72008c74bdc6
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: 8fc9c81b0c9b9c851a44
    clientSecret: 0b77625cee4e63fee9a216333badf991b88ac510
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
google:
  client:
    clientId: 356272807278-bp66n8n799lnvmbipo211bocjhg1mann.apps.googleusercontent.com
    clientSecret: wem9bkKX0JYjoMdIjQdalt--
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: profile email
  resource:
    userInfoUri:  https://www.googleapis.com/oauth2/v3/userinfo